name: Android Build APK CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch: # 支持手动点按钮运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4

      - name: 配置JDK17环境
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 配置Android SDK
        uses: android-actions/setup-android@v3

      - name: 替换阿里云国内镜像（解决谷歌依赖下载失败）
        run: |
          mkdir -p ~/.gradle
          echo "allprojects { repositories { maven { url 'https://maven.aliyun.com/repository/google' } maven { url 'https://maven.aliyun.com/repository/public' } maven { url 'https://maven.aliyun.com/repository/gradle-plugin' } flatDir { dirs 'libs' } } }" > settings.gradle
          chmod +x ./gradlew

      - name: Gradle编译打包Debug APK
        run: ./gradlew assembleDebug

      - name: 上传成品APK到仓库
        uses: actions/upload-artifact@v4
        with:
          name: App-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
